# Generated by Django 3.0.6 on 2020-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20200528_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='phot_url',
            new_name='photo_url',
        ),
    ]
